### ISSUE TITLE
Change Campfire Icons

### ISSUE THREAD

**Issue by cech12** [cech12/UnlitCampfire#1]
DanielGolan suggested to change the texture of the icons of the campfire and the soul campfire. To have no fire.
To differenciate them some red/yellow or blue/white particles should be added.

**Comment by ghost** [comment]
I Am DanielGolan, if somebody asks.

**Comment by cech12** [comment]
Fixed with an additional resource pack; https://www.curseforge.com/minecraft/texture-packs/unlit-campfire-icons
