### ISSUE TITLE
Torches??

### ISSUE THREAD

**Issue by OpticGaze** [cech12/UnlitCampfire#11]
Basically, Torches burn out just like the campfire, but you can use the campfire to light them or even other torches. Going under water can put them out? Putting them away can put them out? You could also start the campfire with a torch or even catch other things on fire??

**Comment by cech12** [comment]
Hey!
Thanks for your interest and idea for this mod. :) 
The focus of this mod is on the campfire. I like your idea to expand the behaviour of torches, but it sounds to me like a dedicated mod out of scope of this mod. And for me there is no plan to create such a mod. :)

For 1.16.5 there is a mod with similar functionality: https://www.curseforge.com/minecraft/mc-mods/realistic-torches

Edit:

For 1.18 & 1.19 there is another mod: https://www.curseforge.com/minecraft/mc-mods/hardcore-torches-forge
