### ISSUE TITLE
[Suggestion] Config for Natural Spawns

### ISSUE THREAD

**Issue by Legomastar** [cech12/UnlitCampfire#12]
If possible, could there be a config to have naturally generated campfires not time out like player-placed ones?
I'm thinking for villages that generate with them as decoration.

**Comment by cech12** [comment]
Thanks for your idea! I like that! :) When I have time, I will look what I can do :)

**Comment by cech12** [comment]
This feature was added and will be released in the next feature update 1.7.0.0.
