### ISSUE TITLE
[Suggestion] Option to Make Campfires Burn Out After Sleep 

### ISSUE THREAD

**Issue by Kabinet0** [cech12/UnlitCampfire#16]
### Describe the Feature

I was wondering if it would be possible to make campfires burn out after sleeping, as (in game) it would have been as if the requisite amount of time had passed. I tested this, but it appears that the campfire only un-lights itself when so many ticks of gameplay have passed, I suggest this me moved to using in game time(as measured by the /query time gametime command or something equivalent). This would allow for the campfire to unlight itself more realistically, and this would of course be configurable.

**Comment by cech12** [comment]
I like your idea! When I have time, I will look into the requested features for this mod and make a new feature release :)
You can follow my work in the linked project. :)

**Comment by cech12** [comment]
This feature was added and will be released in the next feature update 1.7.0.0.
