### ISSUE TITLE
[Feature]: Burn time

### ISSUE THREAD

**Issue by serialtasted** [cech12/UnlitCampfire#17]
### Describe the Feature

Simple suggestion, allow more time until camp fire goes out. I would like to make mine go for 45 minutes
Current limit 10000 ticks

**Comment by cech12** [comment]
There is a config option "campfireLitTime" where you can configure the time a campfire burns.

There is a defaultconfig directory, where you can find the config file. If you change something there it has only an effect on new savegames. For existing savegames you need to go to the serverconfig directory of the savegame.

**Comment by serialtasted** [comment]
Did you read what I wrote?
I know there's a config file, but you have set a limit of 10000 ticks. What I was asking is to remove that limit and allow for it to burn for more time

**Comment by cech12** [comment]
Sorry, I seem to have misunderstood your request. :)

**Comment by cech12** [comment]
The max limit of the following configurations was increased to 2.000.000: campfireLitTime, campfireRainUnlitTime, soulCampfireLitTime, soulCampfireRainUnlitTime

The change is included in the mod versions: 1.18.1-1.5.1.0 & 1.19-1.6.1.0
