### ISSUE TITLE
[Feature]: Can you make Unlit Campfire compatible with Healing Campfire and No Hostiles Around Campfires?

### ISSUE THREAD

**Issue by wumengzhixing** [cech12/UnlitCampfire#18]
### Describe the Feature

When I use 1.18.1-1.5.1.0, I can't let the campfire have the functions of these mods. 
Can you be compatible with them? 
This will be great !
https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire
https://www.curseforge.com/minecraft/mc-mods/healing-campfire

**Comment by cech12** [comment]
Thanks for your report. I will look into that. Some other users sent me that it works great with these mods. Which versions are you using exact? (Forge, other mods versions)

**Comment by wumengzhixing** [comment]
> 谢谢你的报告。我会调查的。其他一些用户给我发来消息说，它可以很好地处理这些插件。你到底用的是哪个版本？(Forge，其他mods版本)
unlitcampfire-forge-1.18.1-1.5.1.0

**Comment by wumengzhixing** [comment]
Sorry, it was an accident. I found a mod conflict. When I only keep these three mods, these functions can work normally.Thank you very much for developing such a great mod.
Have you considered letting players customize the effect?

**Comment by cech12** [comment]
Hey thanks for sharing your findings :) There is a config file where you can configure the unlit-effect :)
https://github.com/cech12/UnlitCampfire/wiki
