### ISSUE TITLE
[Bug]: Infinite Burntime with default settings

### ISSUE THREAD

**Issue by cech12** [cech12/UnlitCampfire#19]
### Minecraft Version

1.18.2

### Mod Loader

Forge

### Mod Loader Version

40.1.52

### Mod Version

1.7.0.0

### Describe the Issue

noodleassault:
I seem to have an issue where the campfires burn infinitely even with default burn time. With oneprobe installed, it looks like it counts down to 1999 ticks left but then freezes there. If I reload the world it'll go to 1998 ticks left, but after that it'll stay at 1998 even after reloading the world

Seems to happen with soul campfire too, and it also says 1999 ticks remaining, which is odd since I think it should start at 2000000 right?

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Canary

**Comment by cech12** [comment]
Seems to be an compatibility issue with Canary

**Comment by Roonas** [comment]
I am having the same issue on 1.19.2 with Canary installed. Campfires set to extinguish in rain will also fail to do so.

**Comment by cech12** [comment]
Yes it is not fixed yet. A workaround could be removing Canary from your mod pack :)

**Comment by cech12** [comment]
Could not be reproduced in actual Canary versions. It looks like, it was fixed in newer Canary versions.

Tested with Canary:
- 0.1.8 (1.18.2)
- 0.2.0 (1.19.2, 1.19.3, 1.19.4)

I think the issue can be closed. :)
