### ISSUE TITLE
[Bug]: Naturally generated campfires can crash the game

### ISSUE THREAD

**Issue by Hanwei233** [cech12/UnlitCampfire#31]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Mod Version

1.9.0.1

### Modpack or other Mod

Any mod that has a campfire structure

### Describe the Issue

Naturally generated structures with campfires have a chance to crash the game

### Logs

https://pastebin.com/1EiNApHS

**Comment by cech12** [comment]
Thanks for your report! I will look into it when I have time! :)

**Comment by cech12** [comment]
A fix will be released in the upcoming versions: 1.19.4-1.7.2.2, 1.20.1-1.9.0.2 and 1.20.4-2.1.0.2
I would love to get feedback if the fix works for your mod pack :) Thanks for your report and have a nice day! :)

**Comment by Hanwei233** [comment]
> 即将发布的版本将发布修复程序：1.19.4-1.7.2.2、1.20.1-1.9.0.2 和 1.20.4-2.1.0.2 如果该修复程序适用于您的 mod 包:)感谢您的报告，祝您有美好的一天！:)

Thank ！
