### ISSUE TITLE
[Feature]: Fire Texture Should indicate remaining burn time

### ISSUE THREAD

**Issue by guivnf** [cech12/UnlitCampfire#32]
### Describe the Feature

So basically this mod is already huge on what it does for campfires. But in my opinion there's just one thing missing, which's having different textures for each certain "level"/burn time thats remaining. For example, you can divide the total burn time by 4 and on each 1/4 thats increased/lessened it'll update the textures to a lower ammount of fire yk, simmilarly to the different fire levels in this game called Don't Starve:
![FireTypes](https://github.com/cech12/UnlitCampfire/assets/77132244/423fca5e-c351-4c2a-928b-c8bc7eb46b05)

**Comment by cech12** [comment]
Thanks for your idea! It was already mentioned in #29 :) I will look into that, when I have time. :)

**Comment by guivnf** [comment]
> Thanks for your idea! It was already mentioned in #29 :) I will look into that, when I have time. :) 

Sorry for the duplicate XD
