### ISSUE TITLE
[Bug]: Lithium making unlit timer infinite

### ISSUE THREAD

**Issue by Anonyku05** [cech12/UnlitCampfire#36]
### Minecraft Version

1.20.4

### Mod Loader

Fabric

### Mod Loader Version

0.97.0

### Mod Version

2.3.0.0

### Modpack or other Mod

[Lithium](https://modrinth.com/mod/lithium)

### Describe the Issue

Lithium makes the unlit timer infinite, meaning the campfire will never burn off, nearly like the unlit campfire mod is not installed

### Logs

https://pastebin.com/4fDHTc88

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Lithium

**Comment by cech12** [comment]
Thanks for your report! I will look into that when I have time :)

**Comment by cech12** [comment]
@Anonyku05 
Unfortunately, Lithium is optimizing campfires in such a way that it does not tick, when no item is on the campfire.

There is a Lithium config option to disable this optimization. You only need to add the following line into the `lithium.properties` config file:
```
mixin.world.block_entity_ticking=false
```
https://github.com/CaffeineMC/lithium-fabric/wiki/Configuration-File#mixinworldblock_entity_ticking

If this isn't enough of a solution for you, I ask you to open an issue at Lithium repository.

Thanks again for your report. :)

**Comment by cech12** [comment]
Since 1.20.4-2.3.0.1 and 1.20.6-2.5.0.1 this mod is compatible with Lithium.

**Comment by CapoFantasma97** [comment]
> Since 1.20.4-2.3.0.1 and 1.20.6-2.5.0.1 this mod is compatible with Lithium.

Any chance to see a version with the fix ported for 1.20.1, being the most commonly used modern version for modding at this time?

**Comment by cech12** [comment]
@CapoFantasma97 The mod is not available for Fabric 1.20.1 and there is no plan to backport it

**Comment by CapoFantasma97** [comment]
> @CapoFantasma97 The mod is not available for Fabric 1.20.1 and there is no plan to backport it

It is available for Forge which has a number of Lithium forks. Well, at least the workaround mentioned in this thread works, although not ideal.

**Comment by cech12** [comment]
Ah! now we are talking about the same thing ^^ I didn't know that there are forks of Lithium for Forge. When I have time, I will look into that :)

**Comment by cech12** [comment]
@CapoFantasma97 Can you send me a link of the Lithium Forge fork you are using?

**Comment by CapoFantasma97** [comment]
> @CapoFantasma97 Can you send me a link of the Lithium Forge fork you are using?

The one with the most traction and the one I use is [Canary](https://github.com/AbdElAziz333/Canary)

Another popular fork is [Radium](https://github.com/Reforged-Hub/radium-upstream)

**Comment by cech12** [comment]
I opened the issues #45 and #46 to support both mods. Canary seems to be an easy addition but Radium has no possibility to support it right now.

**Comment by cech12** [comment]
@CapoFantasma97 the issue is fixed for Canary in the upcoming versions 1.20.1-1.9.1.1, 1.20.4-2.3.1.1, 1.20.6-2.5.1.1 (not tested), 1.21-3.1.1.2 (not tested). For Radium I could not find any issue. :)

**Comment by CapoFantasma97** [comment]
> @CapoFantasma97 the issue is fixed for Canary in the upcoming versions 1.20.1-1.9.1.1, 1.20.4-2.3.1.1, 1.20.6-2.5.1.1 (not tested), 1.21-3.1.1.2 (not tested). For Radium I could not find any issue. :)

Thanks, it works well. Much appreciated
