### ISSUE TITLE
[Feature]: Config option to make the campfire light level decrease as the remaining time on a fire dwindles.

### ISSUE THREAD

**Issue by Acenthus** [cech12/UnlitCampfire#38]
### Describe the Feature

Since the mod is fairly similar to how campfires behave in Don't Starve I feel like it'd be nice to do something like that where campfires have a visual indicator that they're gonna go out soon. Like the title says as the remaining time gets lower and lower the light level decreases, at max it's the max light level beyond a campfire's normal brightness as well.

**Comment by Acenthus** [comment]
Wanted to say I just noticed the idea of texture changes has been mentioned, but I feel like light level might be a bit more fitting.

**Comment by cech12** [comment]
Thanks for your idea! I like it very much :) Maybe it could be a combination of both, a texture and a light level change. I will look into that, when I have time :)

**Comment by cech12** [comment]
I added the feature in the upcoming version 1.21-3.1.1.0. Thanks again for your idea! I hope you enjoy the new feature! :D
