### ISSUE TITLE
Suggestion: don't have campfires extinguish instantly upon rain

### ISSUE THREAD

**Issue by AeiouEnigma** [cech12/UnlitCampfire#4]
It feels very immersion-breaking to have campfires instantly extinguish when rain starts. In my opinion it would be better if the campfires extinguished a short while after rainfall begins, perhaps with some extra smoking effects beforehand.

**Comment by cech12** [comment]
Thanks for your idea, I really liked it! :)

released in 1.3.0
only fabric is missing (I am not a fabric developer. maybe it is ported later to the fabric version)
