### ISSUE TITLE
[Feature]: Older versions update?

### ISSUE THREAD

**Issue by Fer0x453** [cech12/UnlitCampfire#44]
### Describe the Feature

Hi again, finally checked full update info and immediately got a problem that mod didn't update for older versions.

The main question is would you do that (y/n)? Because from my understanding that this kind of mod is relatively easy to update backwards, because it doesn't have a lot of content which you need to transfer. I'm not talking about 1.16 (hell no), I'm talking about relatively old versions like 1.20+.

If it's not really possible, then you have all right to just say "no", it's understandable. My only point that sometimes players (especially in MC) would stay on older versions because there is a particular mechanic or just a lot of old good mods which wont be getting any new updates, so...

**Comment by cech12** [comment]
https://gist.github.com/cech12/662e37d2f8524037d9fef8fbe90bed5a

I add new features to active versions (actually 1.21). Bugs are fixed also in versions which I marked as Legacy (actually all 1.20.x versions). 

You can open a request for a feature which is missing in an 1.20.x version and I will decide if the effort is low enough to port it back to an older version ;)

**Comment by Fer0x453** [comment]
Then I would request to port the feature which I asked before (lit time). If you want specifics I use 1.20.1 forge

**Comment by cech12** [comment]
When I have time I will look into that :)

**Comment by cech12** [comment]
@Fer0x453 I have backported features #38 and #42 to all supported 1.20.x versions:
- 1.20.1-1.9.1.0
- 1.20.4-2.3.1.0
- 1.20.6-2.5.1.0

Have fun! :D

**Comment by Fer0x453** [comment]
Thank you very much! Checked how new version is working and it's perfect.
