### ISSUE TITLE
[Bug]: Campfire appears unlit but after lighting it, it does not burn out, timer does not advance

### ISSUE THREAD

**Issue by Kloytz** [cech12/UnlitCampfire#49]
### Minecraft Version

1.21.1

### Mod Loader

Fabric

### Mod Loader Version

0.16.7

### Mod Version

3.1.1.2

### Modpack or other Mod

Playing a selfmade modpack

### Describe the Issue

When playing on my server at the start of it the campfire worked as intended but after some time, it stopped working maybe because of a mod I updated or added, when trying on singleplayer it also does not burn out.

### Logs

https://mclo.gs/k2M5IOz

**Comment by Kloytz** [comment]
Maybe the best will be If i try 1 by 1 to see which mod is causing the incompatibility

**Comment by cech12** [comment]
@Kloytz thanks for your report! :) Maybe it is an incompatibility with one of your performance enhancing mods like Lithium or Sodium? Maybe the workaround described here could help you: https://github.com/cech12/UnlitCampfire/issues/36
If you find the incompatible mod, please let me know :)
When I have time, I will look into that :)

**Comment by Kloytz** [comment]
seems like it was truly lithium, maybe when i updated to the beta version of lithium it stopped working, cause it was working before.

**Comment by Kloytz** [comment]
![image](https://github.com/user-attachments/assets/fde704bc-ebca-4202-82bd-38ab3f587b6b)
wont this config be more efficient? Since this only toggles campfires and the other config toggles all blocks

**Comment by cech12** [comment]
yes, the workaround was only a quick fix^^ the complete fix seems to be not working with the new beta version. I will look into that :) Thanks for your response :)

**Comment by Kloytz** [comment]
Thanks! For the moment i'll be using mixin.world.block_entity_ticking=false to make the campfires work as intended, since the other mixing from the other issue affects all blocks while this one just affects campfires

**Comment by Kloytz** [comment]
Also this workaround seems to be working for the beta version

**Comment by cech12** [comment]
Fixed in upcoming version 1.21-3.1.1.3. Thanks again for your report! :)
