### ISSUE TITLE
[Bug]: Missing Entries in en_us.json

### ISSUE THREAD

**Issue by stlouisn** [cech12/UnlitCampfire#51]
### Minecraft Version

1.21.1

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### Mod Version

1.21-3.1.1.5

### Describe the Issue

missing language text for config options for:

text.autoconfig.unlitcampfire.option.CAMPFIRE.CAMPFIRE_MAX_LIT_TIME
and all 6 (0-5) @Tooltips

text.autoconfig.unlitcampfire.option.SOUL_CAMPFIRE.SOUL_CAMPFIRE_MAX_LIT_TIME
and all 6 (0-5) @Tooltips

**Comment by cech12** [comment]
Thanks for your report! I will look into that when I have time :)

**Comment by cech12** [comment]
Thanks again for your report! The issue i fixed in the upcoming versions:

- 1.20.4-2.3.1.3
- 1.20.6-2.5.1.3
- 1.21-3.1.1.6
- 1.21.3-3.2.0.2

Have a Merry Christmas! 🎅
