### ISSUE TITLE
Suggestion: Extinguishable Torches

### ISSUE THREAD

**Issue by CapitaineYolo** [cech12/UnlitCampfire#7]
Hey I think it would be neat if torches became finite too, since they are the cheapest lightsource. Im playing on fabric, so I'd be doubly grateful for a port to 1.18 :)

**Comment by cech12** [comment]
Tha ks for your idea and yout interest in this mod. But unlit torches are out of scope of this mod. 

Maybe you are searching a mod like this: https://www.curseforge.com/minecraft/mc-mods/realistic-torches

My mods are developed for Forge. The Fabric port was done by another person. Maybe in the future I would look into mod development for Fabric but for now I don't have enough time for that and it is actually not planned.

**Comment by CapitaineYolo** [comment]
Thats fair, thank you for your quick and thoughful response though :)
