### ISSUE TITLE
Problem download this resource pack ( In curseforge )

### ISSUE THREAD

**Issue by MickeyMouseYT** [cech12/UnlitCampfire#8]
Hello, i try just add for resource pack in modpack i seen which i can't do this i don't know why.

**Comment by MickeyMouseYT** [comment]
![image](https://user-images.githubusercontent.com/78499313/152680689-60924da2-a35a-4191-b1c0-f924b089bb48.png)

**Comment by cech12** [comment]
You want to add this resource pack https://www.curseforge.com/minecraft/texture-packs/unlit-campfire-icons to your minecraft installation and you dont know how to do it?

**Comment by cech12** [comment]
If yes, you only need to download the correct file for your Minecraft version and put it to the resourcepack folder of your Minecraft installation. You can find tons of descriptions how to install a resource pack.

If not, I only give support for this resource pack. If there are connection issues or issues with other mods/modpacks/servers please contact the corresponding developers.
